[package]
name = "giphy-rs"
version = "0.1.0"
authors = ["Maciej Makowski <maciejm.github@cfiet.net>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
iso639-1 = "0.3.0"
dotenv = "0.13.0"
# dotenv_codegen = "0.11.0"
